### ISSUE TITLE
im scared to install this because i wonder if its client sided and wont get you banned

### ISSUE THREAD

**Issue by RobloxLoadingGui** [BGSreal111/ClassicLighting#1]

**Comment by RobloxLoadingGui** [comment]
i need confirmation that this mod is only for the player using it and wont get the player banned

**Comment by BGSreal111** [comment]
> i need confirmation that this mod is only for the player using it and wont get the player banned

No. It Is LocalOnly Wich Means U Wont Get Banned. And also the mod dsoent work right now!

**Comment by RobloxLoadingGui** [comment]
ok thanks ill download it when its fixed
